//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityÜrünProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntityFrameworkEntities : DbContext
    {
        public DBEntityFrameworkEntities()
            : base("name=DBEntityFrameworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblKategori> TblKategori { get; set; }
        public virtual DbSet<TblMüşteri> TblMüşteri { get; set; }
        public virtual DbSet<TblSatış> TblSatış { get; set; }
        public virtual DbSet<TblÜrün> TblÜrün { get; set; }
        public virtual DbSet<TblAdmin> TblAdmin { get; set; }
    
        public virtual ObjectResult<string> MarkaGetir()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MarkaGetir");
        }
    }
}
