//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityÜrünProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMüşteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMüşteri()
        {
            this.TblSatış = new HashSet<TblSatış>();
        }
    
        public int MüşteriID { get; set; }
        public string MüşteriAd { get; set; }
        public string Soyad { get; set; }
        public string Şehir { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSatış> TblSatış { get; set; }
    }
}
